### ISSUE TITLE
bug occured when click image shown in the preview image tile

### ISSUE THREAD

**Issue by Ying-Kang** [ayatough/vscode-image-tile-viewer#29]
I was struggling finding such image tile preview plugins until I find this

It's a great job for achieving the preview like this

However, when I trid to view single image in the preview window, bug occured

I found out that the path in the preview window using "\\"( which was commonly used in windows)

while the absolute path in linux using "/"

which make it hard to view single img triggered from "image tile viewer" by default viewer

```shell
# source img path:
/usr/images/a.jpg

# preview img's path in image tile viewer: 
\usr\image\a.jpg

# which made it impossible for understanding path for linux
```

I'd appreciate it if you could fix the bug 

btw, it's eager for me to call "image tile preview" by right click if you could help

I'm glad to recommend this plugin for my colleagues 

and sincerely waaaiting for your response

Thanks

**Comment by ayatough** [comment]
@Ying-Kang 
Thank you for reporting issue!

> However, when I trid to view single image in the preview window, bug occured

Please let me confirm about the bug.
Are you saying that the tile view is fine, but when you click on an image, the view is broken? (like below image)

![image](https://user-images.githubusercontent.com/28101744/149608051-90a85ab1-60ce-4ca5-b957-e9dcbb176bd0.png)

This is probably caused by an update of VSCode.
I checked and it seems to happen in both windows and linux.
I`d like to investigate about solution.

> btw, it's eager for me to call "image tile preview" by right click if you could help

Thanks for the suggestion!
I'd like to see if I can add an image tile view menu when I left click on a folder in the explorer treeview.

**Comment by ayatough** [comment]
Thank you for nice suggestion and reporting bug!
The feature is added, the bug is fixed in v0.2.2.

**Comment by Ying-Kang** [comment]
wonderful job！cool

**Comment by sawyer7246** [comment]
Such a great extension for me! Nice job.
Actually, I still get this error when I try to preview a single image.  
My VS Code Version@1.65.2.
Pls. help.

**Comment by ayatough** [comment]
Thank you for reporting issue.
I can reproduce it in windows11.
I am researching to fix this issue, but I can`t find solution.
Please wait for some time, sorry.

**Comment by ayatough** [comment]
I can find the solution and fix the problem.
The bug is fixed in v0.2.3.
Thank you.

**Comment by sawyer7246** [comment]
> 
Issue checked.
Thank you so much!
